#pragma once
#include <string>
#include <map>

std::map<std::string, std::string> languages = {
    {"af", "afrikaans"},
    {"ar", "arabic"},
    {"as", "asturianu"},
    {"az", "azerbaijani"},
    {"ba", "bashkir"},
    {"be", "belarusian"},
    {"bg", "bulgarian"},
    {"br", "breton"},
    {"bs", "bosnian"},
    {"ca", "catalan"},
    {"cs", "czech"},
    {"cy", "welsh"},
    {"da", "danish"},
    {"de", "german"},
    {"el", "greek"},
    {"en", "english"},
    {"eo", "esperanto"},
    {"es", "spanish"},
    {"et", "estonian"},
    {"eu", "basque"},
    {"fa", "persian"},
    {"fi", "finnish"},
    {"fil", "filipino"},
    {"fo", "faroese"},
    {"fr", "french"},
    {"fy", "frisian"},
    {"ga", "irish"},
    {"gd", "scottish gaelic"},
    {"gl", "galician"},
    {"gv", "manx"},
    {"ha", "hawaiian"},
    {"he", "hebrew"},
    {"hi", "hindi"},
    {"hr", "croatian"},
    {"hu", "hungarian"},
    {"hy", "armenian"},
    {"id", "indonesian"},
    {"ig", "igbo"},
    {"io", "ido"},
    {"is", "icelandic"},
    {"it", "italian"},
    {"ja", "japanese"},
    {"jb", "lojban"},
    {"ka", "georgian"},
    {"kk", "kazakh"},
    {"kn", "kannada"},
    {"ko", "korean"},
    {"ks", "colognian"},
    {"kw", "cornish"},
    {"la", "latin"},
    {"lb", "luxembourgish"},
    {"li", "limburgish"},
    {"lt", "lithuanian"},
    {"lv", "latvian"},
    {"mi", "maori"},
    {"mk", "macedonian"},
    {"mn", "mongolian"},
    {"ms", "malay"},
    {"mt", "maltese"},
    {"nd", "low german"},
    {"nl", "dutch"},
    {"nn", "norwegian nynorsk"},
    {"no", "norwegian"},
    {"oc", "occitan"},
    {"pl", "polish"},
    {"pt", "portuguese"},
    {"qy", "quenya"},
    {"ro", "romanian"},
    {"ru", "russian"},
    {"se", "northern sami"},
    {"sk", "slovak"},
    {"sl", "slovenian"},
    {"so", "somali"},
    {"sq", "albanian"},
    {"sr", "serbian"},
    {"sv", "swedish"},
    {"sx", "saxon"},
    {"sz", "silesian"},
    {"ta", "tamil"},
    {"th", "thai"},
    {"tl", "tagalog"},
    {"tlh", "klingon"},
    {"tr", "turkish"},
    {"tt", "tatar"},
    {"uk", "ukrainian"},
    {"val", "valencian"},
    {"vec", "venetian"},
    {"vi", "vietnamese"},
    {"yi", "yiddish"},
    {"yo", "yoruba"},
    {"zh", "chinese"}
};

struct message_locale
{
    message_locale(std::map<std::string, std::string> messages_, std::string def)
    :messages(messages_), default_message(def)
    {}
    std::map<std::string, std::string> messages;
    std::string default_message;
};